# Generated by Django 3.2.13 on 2022-05-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0003_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='more_info_link',
            field=models.URLField(default='#'),
        ),
    ]
