# Generated by Django 3.2.13 on 2022-05-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0005_team_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('t', 'Transgender')], max_length=1),
        ),
    ]
