# Generated by Django 3.2.13 on 2022-05-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0007_alter_slider_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
