# Generated by Django 3.2.13 on 2022-05-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0008_auto_20220506_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='edited_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
