# Generated by Django 3.2.13 on 2022-05-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0009_auto_20220506_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='more_info_link',
        ),
        migrations.AddField(
            model_name='team',
            name='yt_link',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
