# Generated by Django 3.2.13 on 2022-05-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0012_about_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chooseus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_experience', models.IntegerField()),
                ('happy_customers', models.IntegerField()),
                ('completed_projects', models.IntegerField()),
                ('happy_creators', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('edited_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('fees', models.IntegerField(blank=True)),
                ('yt_link', models.URLField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('edited_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
