# Generated by Django 3.2.13 on 2022-05-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0015_alter_services_fees'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='title',
            new_name='service_type',
        ),
        migrations.AddField(
            model_name='services',
            name='photo',
            field=models.ImageField(default=0, upload_to='media/services/%Y/%m/'),
            preserve_default=False,
        ),
    ]
