# Generated by Django 3.2.13 on 2022-05-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0016_auto_20220510_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
