# Generated by Django 3.2.13 on 2022-05-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0018_remove_services_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='chooseus',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chooseus',
            name='yt_link',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
