# Generated by Django 3.2.13 on 2022-05-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youtuber',
            old_name='desctiption',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='camera',
            field=models.CharField(choices=[('Canon', 'Canon'), ('Nikon', 'Nikon'), ('Sony', 'Sony')], max_length=10),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='category',
            field=models.CharField(choices=[('lifestyle', 'lifestyle'), ('family', 'family'), ('travel', 'travel'), ('sports', 'sports'), ('tech', 'tech')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='crew',
            field=models.CharField(choices=[('solo', 'solo'), ('team', 'team')], max_length=255),
        ),
    ]
