# Generated by Django 3.2.13 on 2022-05-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0005_alter_youtuber_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtuber',
            name='email',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
