# Generated by Django 3.2.13 on 2022-05-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0007_alter_youtuber_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtuber',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('suspended', 'suspended'), ('hold', 'hold')], default='active', max_length=255),
        ),
    ]
