# Generated by Django 3.2.13 on 2022-05-09 12:28

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiretubers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiretuber',
            name='details',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='hiretuber',
            name='email',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
