# Generated by Django 3.2.13 on 2022-05-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiretubers', '0002_auto_20220509_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiretuber',
            name='city',
            field=models.IntegerField(),
        ),
    ]
