# Generated by Django 3.2.13 on 2022-05-12 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiretubers', '0005_alter_hiretuber_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiretuber',
            name='tuber_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hiretuber',
            name='user_id',
            field=models.CharField(max_length=255),
        ),
    ]
