# Generated by Django 3.2.13 on 2022-05-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiretubers', '0007_hiretuber_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiretuber',
            name='tuber_email',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
