# Generated by Django 3.2.13 on 2022-05-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiretubers', '0010_alter_hiretuber_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiretuber',
            name='status',
            field=models.CharField(default='Screening', max_length=255),
        ),
    ]
